Frontend-SF-13
igorek240101/SimpleFuzzy pull request #14
Opened 2024-07-20 14:41 UTC by AlexSergy

2024-07-22 10:02 UTC, igorek240101 requested changes
Требуется исправление замечаний

2024-07-22 10:02 UTC, igorek240101 commented on SimpleFuzzy/SimpleFuzzy.View/MainWindow.cs
Куда? Зачем основное окно удалили?

2024-07-22 10:02 UTC, igorek240101 commented on SimpleFuzzy/SimpleFuzzy.View/LinguisticVariableUI.cs
> +    public partial class LinguisticVariableForm : Form
Не Form, а UserControl

2024-07-22 10:02 UTC, igorek240101 commented on SimpleFuzzy/SimpleFuzzy.View/LinguisticVariableUI.cs
> +        private TextBox nameTextBox;
Элементы управления лучше вынести в Designer файл

2024-07-22 10:02 UTC, igorek240101 commented on SimpleFuzzy/SimpleFuzzy.View/LinguisticVariableUI.cs
> +        private void InitializeComponent()
вынести в Designer файл

2024-07-22 10:02 UTC, igorek240101 commented on SimpleFuzzy/SimpleFuzzy.View/LinguisticVariableUI.cs
> +        private void InitializeControls()
вынести в Designer файл

2024-07-22 10:02 UTC, igorek240101 commented on SimpleFuzzy/SimpleFuzzy.Model/LinguisticVariable.cs
> +        if (func.Count == 0) func.Add(term);
Логика работает неправильно

2024-07-22 10:02 UTC, igorek240101 commented on SimpleFuzzy/SimpleFuzzy.View/LinguisticVariableUI.cs
> +                termsComboBox.DataSource = null;
Выглядит как костыль, зачем сначала занулять

2024-07-22 10:02 UTC, igorek240101 commented on SimpleFuzzy/SimpleFuzzy.View/LinguisticVariableUI.cs
> +                using (var bitmap = new Bitmap(graphPictureBox.Width, graphPictureBox.Height))
Рисовать руками конечно можно, но я бы предложил воспользоваться готовыми решениями (например OxyPlot) получиться проще, красивее и функциональнее

2024-07-22 10:02 UTC, igorek240101 commented on SimpleFuzzy/SimpleFuzzy.View/TermForm.cs
Вообще не нужное окно

2024-07-25 07:19 UTC, igorek240101 requested changes
Ещё маленькое замечания и конфликты слияния

2024-07-25 07:19 UTC, igorek240101 commented on SimpleFuzzy/SimpleFuzzy.View/MainWindow.Designer.cs
> -            this.Text = "Form1";
Зачем?

2024-07-27 06:20 UTC, igorek240101 approved these changes, later dismissed
Исправить конфликты и можно сливать

2024-08-04 13:40 UTC, MaxMen5 approved these changes

2024-08-04 13:41 UTC, merged