Frontend - Sf 14
igorek240101/SimpleFuzzy pull request #16
Opened 2024-07-22 03:59 UTC by AlexSergy

2024-07-22 10:19 UTC, igorek240101 requested changes
Есть замечания к коду

2024-07-22 10:19 UTC, igorek240101 commented on SimpleFuzzy/SimpleFuzzy.View/GenerationObjectSetUI.cs
> +    public partial class GenerationObjectSetUI : Form
Не Form, а UserControl

2024-07-22 10:19 UTC, igorek240101 commented on SimpleFuzzy/SimpleFuzzy.View/GenerationObjectSetUI.cs
> +                if (step == 0) errorMessage = "��� �� ����� ���� ����� ����.";
Починить кодировку файла

2024-07-22 10:19 UTC, igorek240101 commented on SimpleFuzzy/SimpleFuzzy.View/GenerationObjectSetUI.cs
> +            private void BtnGenerate_Click(object sender, EventArgs e)
По код стайлу C# принято писать слова полностью. Не Btn, а Button

2024-07-22 10:19 UTC, igorek240101 commented on SimpleFuzzy/SimpleFuzzy.View/MainWindow.Designer.cs
Вернуть основное окно приложения на место

2024-07-23 19:45 UTC, igorek240101 requested changes
Ещё есть замечания + не исправлена кодировка

2024-07-23 19:45 UTC, igorek240101 commented on SimpleFuzzy/SimpleFuzzy.View/Program.cs
> +        Application.EnableVisualStyles();
Зачем даунгрейд?
https://learn.microsoft.com/ru-ru/dotnet/core/compatibility/windows-forms/6.0/application-bootstrap

2024-07-23 19:45 UTC, igorek240101 commented on SimpleFuzzy/SimpleFuzzy.View/MainWindow.cs
> +        private void InitializeCustomComponents()
Почему не через конструктор формы?

2024-07-23 19:45 UTC, igorek240101 commented on SimpleFuzzy/SimpleFuzzy.View/MainWindow.Designer.cs
> +            ClientSize = new Size(382, 630);
Зачем здесь изменение размера окна? Это чем-то обосновано?

2024-07-23 19:45 UTC, igorek240101 commented on SimpleFuzzy/SimpleFuzzy.View/MainWindow.Designer.cs
> +            Text = "MainWindow";
Заменить на название нашей программы (SimpleFuzzy)

2024-07-23 23:59 UTC, AlexSergy commented on SimpleFuzzy/SimpleFuzzy.View/MainWindow.Designer.cs
> +            ClientSize = new Size(382, 630);
Окно GenerationObjectUI отличается от окна по умолчанию MainWindow, поначалу я просто поменял размер конструктором, последним коммитом поменяю размер под само окно GenerationObjectUI.

2024-07-24 05:23 UTC, igorek240101 commented on SimpleFuzzy/SimpleFuzzy.View/MainWindow.cs
> +        private void InitializeCustomComponents()
Конструктор form-ы - это Disigner файл, начальные значения задаются там

2024-07-24 05:26 UTC, igorek240101 commented on SimpleFuzzy/SimpleFuzzy.View/MainWindow.Designer.cs
> +            ClientSize = new Size(382, 630);
Здесь задаются начальные характеристики окна, а GenerationObjectUI это не обязательно тот компонент который будет выводиться первым на основном (более того это даже скорее маловероятно), поэтому данное изменение неуместно

2024-07-24 05:28 UTC, igorek240101 commented on SimpleFuzzy/SimpleFuzzy.View/MainWindow.Designer.cs
> +            Text = "MainWindow";
Эта настройка совсем исчезла вместо правильного значения

2024-07-24 05:32 UTC, igorek240101 requested changes
Не все проблемы решены. Конфликты не исправлены

2024-07-24 05:32 UTC, igorek240101 commented on SimpleFuzzy/SimpleFuzzy.View/MainWindow.Designer.cs
> +            Name = "SimpleFuzzy";
MainWindow

2024-07-24 05:32 UTC, igorek240101 commented on SimpleFuzzy/SimpleFuzzy.View/MainWindow.Designer.cs
> +            Text = "Генератор кода базовых множеств";
Основное окно не является Генератором кода базовых множеств. Должно быть SimpleFuzzy

2024-07-25 12:46 UTC, igorek240101 commented on SimpleFuzzy/SimpleFuzzy.View/MainWindow.Designer.cs
> +            ClientSize = new Size(382, 630);
Новое значение убрано, а старое не вернули

2024-07-25 12:47 UTC, igorek240101 requested changes
С размером окна доработать конфликты слияния исправить

2024-07-27 14:28 UTC, igorek240101 approved these changes, later dismissed
Исправить конфликты

2024-07-30 15:47 UTC, igorek240101 approved these changes

2024-07-30 15:48 UTC, merged