Frontend-SF-15
igorek240101/SimpleFuzzy pull request #19
Opened 2024-07-25 01:49 UTC by AlexSergy

2024-07-25 13:54 UTC, igorek240101 requested changes

2024-07-25 13:54 UTC, igorek240101 commented on SimpleFuzzy/SimpleFuzzy.View/GenerationMembershipUI.cs
> +                PlaceholderText = "���������"
Починить кодировку

2024-07-25 13:54 UTC, igorek240101 commented on SimpleFuzzy/SimpleFuzzy.View/GenerationMembershipUI.cs
> +                Console.WriteLine($"������ ��� ������ �������: {ex.Message}");
Какая консоль? У нас в проекте нет никакой консоли

2024-07-25 13:54 UTC, igorek240101 commented on SimpleFuzzy/SimpleFuzzy.View/GenerationMembershipUI.cs
> +                Console.WriteLine($"������ ��� ������ ���������: {ex.Message}");
Какая консоль? У нас в проекте нет никакой консоли

2024-07-25 22:59 UTC, AlexSergy commented on SimpleFuzzy/SimpleFuzzy.View/GenerationMembershipUI.cs
> +                Console.WriteLine($"������ ��� ������ �������: {ex.Message}");
Прошу прощения, по невнимательности

2024-07-27 15:52 UTC, igorek240101 submitted a review, later dismissed
Разрешить конфликты

2024-07-30 15:39 UTC, igorek240101 approved these changes

2024-07-30 15:44 UTC, merged