SF-37
igorek240101/SimpleFuzzy pull request #27
Opened 2024-07-30 12:33 UTC by MaxMen5

2024-07-30 12:36 UTC, MaxMen5 commented
https://etu-apu-9371.youtrack.cloud/issue/SF-37/Vnedrenie-zavisimostej-v-MainWindow

2024-07-30 13:50 UTC, igorek240101 requested changes
Несколько мелких правок + 
Мысли о том как в принципе избавить от зависимости с MainWindow:
можно использовать свойство Parent чтобы получить родительский элемент. А там где нужно не посредственно обратиться к функциям основного окна сделать каст через as

2024-07-30 13:50 UTC, igorek240101 commented on SimpleFuzzy/SimpleFuzzy.Service/ProjectsListService.cs
> +        private string? currentProjectName;
Неиспользуемое поле

2024-07-30 13:50 UTC, igorek240101 commented on SimpleFuzzy/SimpleFuzzy.View/AutofacConfig.cs
> -        builder.RegisterType<Repository>().As<IRepository>();
Удалена регистрация одного из нужных сервисов

2024-07-30 18:46 UTC, igorek240101 requested changes
Не используемое поле осталось неиспользуемым + ещё 2 наблюдения сделал

2024-07-30 18:46 UTC, igorek240101 commented on SimpleFuzzy/SimpleFuzzy.Service/RepositoryService.cs
> +public class RepositoryService : IRepository
Разумное переименование. Давайте тогда ещё и интерфейс соответственно переименуем

2024-07-30 18:46 UTC, igorek240101 commented on SimpleFuzzy/SimpleFuzzy.View/ConfirmCopy.cs
> +            if (Parent is MainWindow parent) { parent.OpenButtons(sender, e); }
А зачем собственно передавать в методы: Locked, OpenButtons и BlockButtons аргументы?
Они как таковыми обработчиками событий не являются, сами аргументы внутри не используются, да и передаваемые значения смысла для MainWindow особо не имеют

2024-07-31 11:11 UTC, igorek240101 approved these changes

2024-07-31 11:11 UTC, merged