SF-27
igorek240101/SimpleFuzzy pull request #29
Opened 2024-07-30 19:02 UTC by Beq4ch

2024-07-30 19:36 UTC, igorek240101 requested changes

2024-07-30 19:36 UTC, igorek240101 commented on SimpleFuzzy/SimpleFuzzy.Service/Repository.cs
> -    private readonly List<ISimulator> _simulators;
Зачем удаление в этом файле?

2024-07-30 19:36 UTC, igorek240101 commented on SimpleFuzzy/SimpleFuzzy.View/HelpWindow.cs
> +        private void treeView1_AfterSelect(object sender, TreeViewEventArgs e)
Убрать пустой обработчик

2024-07-30 19:36 UTC, igorek240101 commented on SimpleFuzzy/SimpleFuzzy.View/MainWindow.Designer.cs
> -            button1.Location = new Point(0, 0);
Зачем изменены параметры визуального отображения компонентов из других задач?

2024-07-30 20:20 UTC, Beq4ch commented on SimpleFuzzy/SimpleFuzzy.Service/Repository.cs
> -    private readonly List<ISimulator> _simulators;
С ними у меня возникают ошибки сборки
![изображение_2024-07-30_224312318](https://github.com/user-attachments/assets/da65798d-1b3b-4ac2-ba76-ea5c48bf31bf)

2024-07-30 21:13 UTC, igorek240101 commented on SimpleFuzzy/SimpleFuzzy.Service/Repository.cs
> -    private readonly List<ISimulator> _simulators;
Надо подлить свежие изменения из develop ветки. Такое случается иногда. Если кто-то сильно поменял код с тех пор как начата работа над задачей. 
![image](https://github.com/user-attachments/assets/b5885484-2373-4f56-9574-00c90592376a)
После этого проблем с этими строчками быть не должно

2024-08-04 12:46 UTC, MaxMen5 approved these changes

2024-08-04 12:49 UTC, MaxMen5 approved these changes

2024-08-04 12:50 UTC, MaxMen5 approved these changes

2024-08-04 14:11 UTC, closed without merging